# This is a basic workflow to help you get started with Actions
import java.util.Scanner;

public class TreasureHunterSimulator {

    private static final double MAX_DISTANCE = 10.0; // maksimal masofa (metrda)
    private static final double SIGNAL_THRESHOLD = 6.0; // 6 metr - signal boshlanishi
    private static final double CLOSE_THRESHOLD = 3.0; // 3 metr - qattiq signal

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        double distance = MAX_DISTANCE; // boshlang'ich masofa
        
        System.out.println("Til qidiruvchi dastur ishga tushdi!");
        System.out.println("Masofani kiriting (metrda) yoki 'topdim' deb yozing:");

        while (true) {
            String input = scanner.nextLine();
            
            if (input.equalsIgnoreCase("topdim")) {
                System.out.println("Tabriklaymiz! Til topildi 🎉");
                break;
            }

            try {
                distance = Double.parseDouble(input);
                
                if (distance <= 0) {
                    System.out.println("Til topildi! BEEP BEEP BEEP 🔊🔊🔊");
                    break;
                } else if (distance <= CLOSE_THRESHOLD) {
                    System.out.println("Judayam yaqin! BEEP BEEP BEEP 🔊🔊🔊");
                } else if (distance <= SIGNAL_THRESHOLD) {
                    System.out.println("Signal: ... beep ...");
                } else {
                    System.out.println("Signal yo'q (6 metrdan uzoqda)");
                }
            } catch (NumberFormatException e) {
                System.out.println("Noto'g'ri kiritish! Masofani raqamda kiriting yoki 'topdim' deb yozing.");
            }
        }
        scanner.close();
    }
}
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
